@url = https://bbc-meetupgetup-mern-backend.herokuapp.com
 
## TEST
GET {{url}}/meetups
 
### LOGIN
POST {{url}}/login
content-type: application/json
 
{
    "username": "harold",
    "password": "finch123"
}
 
### MAINTAIN LOGIN
POST {{url}}/maintain-login
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiaGFyb2xkIiwiZmlyc3ROYW1lIjoiSGFyb2xkIiwibGFzdE5hbWUiOiJGaW5jaCIsImFjY2Vzc0dyb3VwcyI6WyJsb2dnZWRJblVzZXJzIiwiam9iU2Vla2VycyJdfSwiaWF0IjoxNjU4NDA4MjIwLCJleHAiOjE2NTg0MDgyNzB9.PZjO4O4FrJdYoRaNZyfyZYq8rVb7m-5mInnx2xXqcX0